# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# CodeRabbit Configuration for UltraCoach
# AI-powered code review for ultramarathon coaching platform

# Language and tone configuration
language: 'en-US'
tone_instructions: 'Be constructive and provide actionable feedback while maintaining a professional, supportive tone.'

# Review settings
reviews:
  # Profile for review depth
  profile: 'assertive' # More thorough feedback for production code

  # Enable auto-review on all PRs
  auto_review:
    enabled: true
    drafts: false
    # Automatic incremental reviews on each push
    auto_incremental_review: true

  # Path filtering (replaces top-level 'ignore')
  path_filters:
    - '!node_modules/**'
    - '!.next/**'
    - '!dist/**'
    - '!build/**'
    - '!.env*'
    - '!*.min.js'
    - '!*.min.css'
    - '!.context7-docs/**'
    - '!coverage/**'
    - '!.playwright/**'
    # Include all other files
    - '**/*'

  # Review instructions (keeping your existing ones)
  path_instructions:
    # TypeScript and TSX files
    - path: '**/*.{ts,tsx}'
      instructions: |
        Review TypeScript/React code against the following standards:
        - Ensure proper TypeScript types (no 'any' types unless absolutely necessary)
        - Check for React 19 best practices and modern patterns
        - Verify Jotai state management patterns are correctly implemented
        - Ensure proper use of Server/Client Component hybrid pattern for Next.js 15
        - Check for proper error handling with tslog (no console.log)
        - Verify HeroUI component usage follows Mountain Peak design system
        - Check for performance optimizations (memoization, lazy loading)
        - Ensure accessibility standards are met

    # Test files
    - path: '**/*.spec.{ts,tsx}'
      instructions: |
        Review Playwright test code for:
        - Proper test structure and naming conventions
        - Appropriate use of page objects and selectors
        - Comprehensive test coverage for critical user flows
        - Proper cleanup and test isolation
        - Avoid using networkidle for real-time applications

    # API routes
    - path: '**/api/**/*.{ts,tsx}'
      instructions: |
        Review API routes for:
        - Proper authentication with Better Auth
        - Input validation and sanitization
        - Error handling and appropriate status codes
        - Database query optimization with Drizzle ORM
        - Rate limiting considerations
        - Security best practices (no exposed secrets)
        - Correct fetch credentials usage (same-origin for internal APIs)

    # Database and schema files
    - path: '**/schema.ts'
      instructions: |
        Review database schema for:
        - Proper Drizzle ORM patterns
        - Appropriate indexes for performance
        - Data integrity constraints
        - Better Auth compatibility (role vs userType fields)

    # Styling files
    - path: '**/*.css'
      instructions: |
        Review CSS for:
        - Tailwind CSS v3 best practices
        - Proper use of Mountain Peak design system colors
        - Mobile-first responsive design
        - Performance considerations (avoid excessive gradients)

    # Configuration files
    - path: '**/*.{json,yaml,yml}'
      instructions: |
        Review configuration files for:
        - No hardcoded secrets or sensitive data
        - Proper environment variable usage
        - Consistent formatting

    # HTTP client patterns
    - path: '**/*.{ts,tsx}'
      instructions: |
        Review fetch calls for proper credentials usage:
        - Use 'credentials: same-origin' for all internal /api/* endpoints
        - Use 'credentials: include' ONLY for cross-origin requests
        - Use 'credentials: omit' for public APIs
        - Prefer relative URLs (/api/...) over absolute URLs
        - Ensure consistent error handling and proper Content-Type headers

  # Tools configuration
  tools:
    # AST-based code analysis
    ast-grep:
      essential_rules: true

    # ESLint integration
    eslint:
      enabled: true

    # Security scanning (replaces top-level 'security')
    gitleaks:
      enabled: true

  # Walkthrough options
  high_level_summary: true
  sequence_diagrams: true
  changed_files_summary: true
  estimate_code_review_effort: true

  # Pre-merge checks
  pre_merge_checks:
    docstrings:
      mode: 'warning'
      threshold: 80
    title:
      mode: 'warning'
      requirements: 'Title should be concise and descriptive, ideally under 50 characters.'
    description:
      mode: 'warning'

# Code generation settings
code_generation:
  docstrings:
    enabled: true
    path_instructions:
      - path: '**/*.{ts,tsx}'
        instructions: |
          Generate JSDoc-style documentation with TypeScript types.
          Include @param, @returns, and @throws tags where applicable.

# Knowledge base integration
knowledge_base:
  # Enable issue linking (replaces top-level 'issues')
  issues:
    scope: 'auto'

  # Optional: Enable learnings from previous reviews
  learnings:
    scope: 'local'
