#!/usr/bin/env tsx
import { config } from 'dotenv'
import * as fs from 'fs'
import { resolve } from 'path'

import { createLogger } from '../src/lib/logger'

// Load environment variables
config({ path: resolve(process.cwd(), '.env.local') })

const logger = createLogger('seed-users-better-auth')

// Test users with their passwords and roles
const testUsers = [
  {
    email: 'coach1@ultracoach.dev',
    password: 'password123',
    name: 'Elena Rodriguez',
    role: 'coach',
    fullName: 'Elena Rodriguez',
  },
  {
    email: 'coach2@ultracoach.dev',
    password: 'password123',
    name: 'Sarah Mountain',
    role: 'coach',
    fullName: 'Sarah Mountain',
  },
  {
    email: 'testrunner@ultracoach.dev',
    password: 'password123',
    name: 'Alex Trail',
    role: 'runner',
    fullName: 'Alex Trail',
  },
  {
    email: 'runner2@ultracoach.dev',
    password: 'password123',
    name: 'Mike Trailblazer',
    role: 'runner',
    fullName: 'Mike Trailblazer',
  },
]

async function signUpUser(userData: (typeof testUsers)[0]) {
  const response = await fetch('http://localhost:3001/api/auth/sign-up/email', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      email: userData.email,
      password: userData.password,
      name: userData.name,
      role: userData.role,
      fullName: userData.fullName,
    }),
  })

  if (!response.ok) {
    const error = await response.text()
    throw new Error(`HTTP ${response.status}: ${error}`)
  }

  return await response.json()
}

async function clearExistingUsers() {
  logger.info('🗑️ Clearing existing users and accounts...')

  const { db } = await import('../../src/lib/database')
  const schema = await import('../../src/lib/schema')

  // Delete accounts first (due to foreign key constraints)
  await db.delete(schema.account)
  await db.delete(schema.user)

  logger.info('✅ Cleared existing users and accounts')
}

async function createTestUsers() {
  logger.info('👥 Creating test users via Better Auth sign-up API...')

  for (const userData of testUsers) {
    try {
      logger.info(`Creating user: ${userData.email}`)

      const result = await signUpUser(userData)
      logger.info(`✅ Created user: ${userData.email} (${userData.role})`)
    } catch (error) {
      logger.error(`❌ Error creating ${userData.email}:`, error)
    }
  }
}

function updateEnvLocal() {
  const envPath = resolve(process.cwd(), '.env.local')
  let envContent = ''

  // Read existing .env.local if it exists
  if (fs.existsSync(envPath)) {
    envContent = fs.readFileSync(envPath, 'utf8')
  }

  // Remove existing test user credentials from env content
  const testUserKeys = [
    'TEST_COACH_EMAIL',
    'TEST_COACH_PASSWORD',
    'TEST_COACH2_EMAIL',
    'TEST_COACH2_PASSWORD',
    'TEST_RUNNER_EMAIL',
    'TEST_RUNNER_PASSWORD',
    'TEST_RUNNER2_EMAIL',
    'TEST_RUNNER2_PASSWORD',
  ]

  // Remove old test user lines
  const lines = envContent.split('\n').filter(line => {
    const key = line.split('=')[0]
    return !testUserKeys.includes(key) && !line.startsWith('# Test user credentials')
  })

  // Add updated test user credentials
  lines.push('')
  lines.push('# Test user credentials (auto-generated by Better Auth seed script)')

  const roleCounters = { coach: 0, runner: 0 }
  testUsers.forEach(user => {
    roleCounters[user.role as 'coach' | 'runner']++
    const role = user.role.toUpperCase()
    const suffix =
      roleCounters[user.role as 'coach' | 'runner'] > 1
        ? roleCounters[user.role as 'coach' | 'runner'].toString()
        : ''
    const roleKey = `${role}${suffix}`

    lines.push(`TEST_${roleKey}_EMAIL=${user.email}`)
    lines.push(`TEST_${roleKey}_PASSWORD=${user.password}`)
  })

  lines.push('')

  // Write updated content back to .env.local
  fs.writeFileSync(envPath, lines.join('\n'))
  logger.info(`✅ Updated .env.local with test user credentials`)
}

async function main() {
  try {
    logger.info('🌱 Starting Better Auth user seeding...')

    // Clear existing users first
    await clearExistingUsers()

    // Update .env.local with credentials
    updateEnvLocal()

    // Create test users via Better Auth API
    await createTestUsers()

    logger.info('✅ Better Auth user seeding completed')
    console.log(`
🎯 Test users created! Use these credentials to login:
• coach1@ultracoach.dev / password123 (Coach)
• coach2@ultracoach.dev / password123 (Coach)  
• testrunner@ultracoach.dev / password123 (Runner)
• runner2@ultracoach.dev / password123 (Runner)
    `)
    process.exit(0)
  } catch (error) {
    logger.error('❌ Better Auth user seeding failed:', error)
    process.exit(1)
  }
}

if (require.main === module) {
  main()
}
